# Generated by Django 4.1.3 on 2025-07-22 07:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PartnerFindingProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('biography', models.TextField(default='')),
                ('appear_in_search', models.BooleanField(default=True)),
                ('language_proficiency', models.TextField(blank=True, choices=[('A', 'A'), ('B', 'B'), ('C', 'C')])),
                ('learning_goal', models.TextField(blank=True, choices=[('Academia', 'aca'), ('Business', 'bus'), ('Hobby', 'hbb')])),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-updated_at'],
            },
        ),
    ]
